require 'tests/lib/dragon_skeleton/animations.rb'
require 'tests/lib/dragon_skeleton/buttons.rb'
require 'tests/lib/dragon_skeleton/file_formats/aseprite_json.rb'
require 'tests/lib/dragon_skeleton/long_calculation.rb'
require 'tests/lib/dragon_skeleton/pathfinding.rb'
require 'tests/lib/dragon_skeleton/pathfinding/a_star.rb'
require 'tests/lib/dragon_skeleton/pathfinding/priority_queue.rb'
